[package]
name = "simple_string_lexer"
version = "0.1.0"
edition = "2021"
description = "Splits strings by whitespace and quoted groups."
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
